Resources:
  PrivateBinTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}
      AttributeDefinitions:
        - AttributeName: noteId
          AttributeType: S
      KeySchema:
        - AttributeName: noteId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: timeToLive
        Enabled: true

  UserAccountTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.userAccountTable}
      AttributeDefinitions:
        - AttriobuteName: userId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecyfycation:
        AttributeName: timeToLive
        Enabled: true
